[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs.audits]
  performance = true
  accessibility = true
  best-practices = true
  seo = true
  pwa = true

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true